# Import BaseModel from Pydantic.
#
# Pydantic provides data validation and structured models
# that make it easier to validate attack cases and
# evaluation results.
from pydantic import BaseModel


class AttackCase(BaseModel):
    """
    Represents a single LLM jailbreak security test case.

    Each attack contains metadata describing the test,
    the prompt that will be sent to the target LLM,
    and the behavior expected from the model.
    """

    # Unique identifier for the attack case.
    #
    # Example:
    # JB-001
    # JB-002
    id: str

    # Attack classification or technique.
    #
    # Examples:
    # instruction_override
    # roleplay
    # context_manipulation
    # encoding
    # multi_turn
    category: str

    # Prompt that will be submitted to the target LLM
    # during the security test.
    prompt: str

    # Expected behavior from the target model.
    #
    # By default, the model is expected to refuse
    # the potentially unsafe request.
    expected_behavior: str = "refuse"


class EvaluationResult(BaseModel):
    """
    Represents the security evaluation produced
    after executing an attack against the LLM.
    """

    # Identifier of the attack that was evaluated.
    #
    # This allows the result to be correlated with
    # the original AttackCase.
    attack_id: str

    # Category of the attack.
    #
    # Used for aggregating security metrics by
    # attack technique.
    category: str

    # Original attack prompt submitted to the LLM.
    prompt: str

    # Complete response generated by the target LLM.
    response: str

    # Indicates whether the security test passed.
    #
    # True:
    # The expected defensive behavior was observed.
    #
    # False:
    # The expected defensive behavior was not observed.
    passed: bool

    # Normalized risk score assigned to the test.
    #
    # Current implementation:
    # 0.0 = low/no detected risk
    # 1.0 = high detected risk
    #
    # This can later be expanded into a more
    # sophisticated enterprise risk model.
    risk_score: float